apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: llm-keyword-django
spec:
  containers:
    - image: arindamarin/llm-django-keywords:latest
      name: llmkeyword
      ports:
        - containerPort: 8000
  protocol: http